name: release

on:
  push:
    tags:        
      - "*"

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Sign into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current datetime
        run: echo "DATETIME=$(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.created={{ env.DATETIME }}
            org.opencontainers.image.title={{ github.event.repository.name }}
            org.opencontainers.image.revision={{ github.sha }}
            org.opencontainers.image.version={{ env.tag }}
            org.opencontainers.image.source={{ github.server_url }}/{{ github.repository }}
